In [232]:
import pandas as pd
import numpy as np

In [233]:
data = [{'x1': 5, 'x2' :0.7, 'x3' :7.200, 'class' :1},{'x1': 4, 'x2' :0.3, 'x3' :3.278, 'class' :2},{'x1': 7, 'x2' :0.8, 'x3' :8.110, 'class' :2}
       ,{'x1': 8, 'x2' :0.6, 'x3' :6.356, 'class' :2},{'x1': 3, 'x2' :0.6, 'x3' :6.001, 'class' :1},{'x1': 2, 'x2' :0.5, 'x3' :5.342, 'class' :1}
       ,{'x1': 9, 'x2' :0.6, 'x3' :6.220, 'class' :2}]

In [234]:
test =pd.DataFrame(data)

In [235]:
test

x1   x2     x3  class
0   5  0.7  7.200      1
1   4  0.3  3.278      2
2   7  0.8  8.110      2
3   8  0.6  6.356      2
4   3  0.6  6.001      1
5   2  0.5  5.342      1
6   9  0.6  6.220      2

In [236]:
num = test.iloc[:,:-1]

In [237]:
num

x1   x2     x3
0   5  0.7  7.200
1   4  0.3  3.278
2   7  0.8  8.110
3   8  0.6  6.356
4   3  0.6  6.001
5   2  0.5  5.342
6   9  0.6  6.220

In [238]:
test["x1"]

0    5
1    4
2    7
3    8
4    3
5    2
6    9
Name: x1, dtype: int64

In [239]:
(test["x1"]-test["x1"].min())/(test["x1"].max() - test["x1"].min())

0    0.428571
1    0.285714
2    0.714286
3    0.857143
4    0.142857
5    0.000000
6    1.000000
Name: x1, dtype: float64

In [240]:
(test["x2"]-test["x2"].min())/(test["x2"].max() - test["x2"].min())

0    0.8
1    0.0
2    1.0
3    0.6
4    0.6
5    0.4
6    0.6
Name: x2, dtype: float64

In [241]:
(test["x3"]-test["x3"].min())/(test["x3"].max() - test["x3"].min())

0    0.811672
1    0.000000
2    1.000000
3    0.637003
4    0.563535
5    0.427152
6    0.608858
Name: x3, dtype: float64

In [242]:
from sklearn import preprocessing

In [243]:
minmax_scalar = preprocessing.MinMaxScaler().fit(test[["x1","x2","x3"]])

In [244]:
df_minmax = minmax_scalar.transform(test[["x1","x2","x3"]])

In [245]:
df_minmax

array([[0.42857143, 0.8       , 0.81167219],
       [0.28571429, 0.        , 0.        ],
       [0.71428571, 1.        , 1.        ],
       [0.85714286, 0.6       , 0.63700331],
       [0.14285714, 0.6       , 0.56353477],
       [0.        , 0.4       , 0.42715232],
       [1.        , 0.6       , 0.60885762]])

In [246]:
df_minmax =pd.DataFrame(df_minmax,columns=['x1','x2','x3'])

In [247]:
out = pd.concat([df_minmax,test.iloc[:,-1:]],axis=1)

In [248]:
out.columns

Index(['x1', 'x2', 'x3', 'class'], dtype='object')

In [249]:
out

x1   x2        x3  class
0  0.428571  0.8  0.811672      1
1  0.285714  0.0  0.000000      2
2  0.714286  1.0  1.000000      2
3  0.857143  0.6  0.637003      2
4  0.142857  0.6  0.563535      1
5  0.000000  0.4  0.427152      1
6  1.000000  0.6  0.608858      2

In [258]:
out.iloc[6:,:3]

x1   x2        x3
6  1.0  0.6  0.608858

In [259]:
out['distance0'] = out[['x1','x2','x3']].sub(np.array(out.iloc[:1,:3])).pow(2).sum(1).pow(0.5)
out['distance1'] = out[['x1','x2','x3']].sub(np.array(out.iloc[1:2,:3])).pow(2).sum(1).pow(0.5)
out['distance2'] = out[['x1','x2','x3']].sub(np.array(out.iloc[2:3,:3])).pow(2).sum(1).pow(0.5)
out['distance3'] = out[['x1','x2','x3']].sub(np.array(out.iloc[3:4,:3])).pow(2).sum(1).pow(0.5)
out['distance4'] = out[['x1','x2','x3']].sub(np.array(out.iloc[4:5,:3])).pow(2).sum(1).pow(0.5)
out['distance5'] = out[['x1','x2','x3']].sub(np.array(out.iloc[5:6,:3])).pow(2).sum(1).pow(0.5)
out['distance6'] = out[['x1','x2','x3']].sub(np.array(out.iloc[6:,:3])).pow(2).sum(1).pow(0.5)

In [260]:
out

x1   x2        x3  class  distance0  distance1  distance2  distance3  \
0  0.428571  0.8  0.811672      1   0.000000   1.148573   0.396358   0.504165   
1  0.285714  0.0  0.000000      2   1.148573   0.000000   1.477726   1.045133   
2  0.714286  1.0  1.000000      2   0.396358   1.477726   0.000000   0.558726   
3  0.857143  0.6  0.637003      2   0.504165   1.045133   0.558726   0.000000   
4  0.142857  0.6  0.563535      1   0.428024   0.835452   0.822820   0.718054   
5  0.000000  0.4  0.427152      1   0.701091   0.651223   1.094696   0.904838   
6  1.000000  0.6  0.608858      2   0.638486   1.113962   0.628192   0.145603   

   distance4  distance5  distance6  
0   0.428024   0.701091   0.638486  
1   0.835452   0.651223   1.113962  
2   0.822820   1.094696   0.628192  
3   0.718054   0.904838   0.145603  
4   0.000000   0.281084   0.858340  
5   0.281084   0.000000   1.035865  
6   0.858340   1.035865   0.000000

In [261]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

In [262]:
fitted = std_scaler.fit(num)

In [263]:
num = std_scaler.transform(num)

In [264]:
num

array([[-0.17556172,  0.78446454,  0.8009614 ],
       [-0.58520574, -1.96116135, -1.98500012],
       [ 0.64372631,  1.47087101,  1.44737267],
       [ 1.05337032,  0.09805807,  0.20143271],
       [-0.99484975,  0.09805807, -0.05073872],
       [-1.40449377, -0.58834841, -0.51885413],
       [ 1.46301434,  0.09805807,  0.10482619]])

In [266]:
result =pd.DataFrame(num,columns=['x1','x2','x3'])

In [267]:
result

x1        x2        x3
0 -0.175562  0.784465  0.800961
1 -0.585206 -1.961161 -1.985000
2  0.643726  1.470871  1.447373
3  1.053370  0.098058  0.201433
4 -0.994850  0.098058 -0.050739
5 -1.404494 -0.588348 -0.518854
6  1.463014  0.098058  0.104826

In [268]:
output = pd.concat([result,test.iloc[:,-1:]],axis=1)

In [269]:
output

x1        x2        x3  class
0 -0.175562  0.784465  0.800961      1
1 -0.585206 -1.961161 -1.985000      2
2  0.643726  1.470871  1.447373      2
3  1.053370  0.098058  0.201433      2
4 -0.994850  0.098058 -0.050739      1
5 -1.404494 -0.588348 -0.518854      1
6  1.463014  0.098058  0.104826      2

In [272]:
output['distance0'] = output[['x1','x2','x3']].sub(np.array(output.iloc[:1,:3])).pow(2).sum(1).pow(0.5)
output['distance1'] = output[['x1','x2','x3']].sub(np.array(output.iloc[1:2,:3])).pow(2).sum(1).pow(0.5)
output['distance2'] = output[['x1','x2','x3']].sub(np.array(output.iloc[2:3,:3])).pow(2).sum(1).pow(0.5)
output['distance3'] = output[['x1','x2','x3']].sub(np.array(output.iloc[3:4,:3])).pow(2).sum(1).pow(0.5)
output['distance4'] = output[['x1','x2','x3']].sub(np.array(output.iloc[4:5,:3])).pow(2).sum(1).pow(0.5)
output['distance5'] = output[['x1','x2','x3']].sub(np.array(output.iloc[5:6,:3])).pow(2).sum(1).pow(0.5)
output['distance6'] = output[['x1','x2','x3']].sub(np.array(output.iloc[6:,:3])).pow(2).sum(1).pow(0.5)

In [275]:
output

x1        x2        x3  class  distance0  distance1  distance2  \
0 -0.175562  0.784465  0.800961      1   0.000000   3.932919   1.249093   
1 -0.585206 -1.961161 -1.985000      2   3.932919   0.000000   5.007025   
2  0.643726  1.470871  1.447373      2   1.249093   5.007025   0.000000   
3  1.053370  0.098058  0.201433      2   1.529988   3.421375   1.898628   
4 -0.994850  0.098058 -0.050739      1   1.366667   2.854743   2.610342   
5 -1.404494 -0.588348 -0.518854      1   2.266451   2.169201   3.507369   
6  1.463014  0.098058  0.104826      2   1.908059   3.578123   2.087649   

   distance3  distance4  distance5  distance6  
0   1.529988   1.366667   2.266451   1.908059  
1   3.421375   2.854743   2.169201   3.578123  
2   1.898628   2.610342   3.507369   2.087649  
3   0.000000   2.063685   2.651615   0.420881  
4   2.063685   0.000000   0.926334   2.462782  
5   2.651615   0.926334   0.000000   3.013757  
6   0.420881   2.462782   3.013757   0.000000

In [ ]:
np.array(6,0.7)

In [ ]:
output['distance_new1'] = output[['x1','x2','x3']].sub(np.array()).pow(2).sum(1).pow(0.5)

In [276]:
data2 = [{'x1': 5, 'x2' :0.7, 'x3' :7.200, 'class' :1},{'x1': 4, 'x2' :0.3, 'x3' :3.278, 'class' :2},{'x1': 7, 'x2' :0.8, 'x3' :8.110, 'class' :2}
       ,{'x1': 8, 'x2' :0.6, 'x3' :6.356, 'class' :2},{'x1': 3, 'x2' :0.6, 'x3' :6.001, 'class' :1},{'x1': 2, 'x2' :0.5, 'x3' :5.342, 'class' :1}
       ,{'x1': 9, 'x2' :0.6, 'x3' :6.220, 'class' :2},{'x1': 6, 'x2' :0.7, 'x3' :6.666, 'class' :0}]

In [277]:
test2 =pd.DataFrame(data2)

In [278]:
num2 = test2.iloc[:,:-1]

In [279]:
fitted2 = std_scaler.fit(num2)

In [280]:
num2 = std_scaler.transform(num2)

In [281]:
result2 =pd.DataFrame(num2,columns=['x1','x2','x3'])

In [282]:
result2

x1        x2        x3
0 -0.218218  0.707107  0.791177
1 -0.654654 -2.121320 -2.154590
2  0.654654  1.414214  1.474667
3  1.091089  0.000000  0.157259
4 -1.091089  0.000000 -0.109377
5 -1.527525 -0.707107 -0.604344
6  1.527525  0.000000  0.055111
7  0.218218  0.707107  0.390096

In [298]:
output2 = pd.concat([result2
                     ,test2.iloc[:,-1:]],axis=1)

In [299]:
output2

x1        x2        x3  class
0 -0.218218  0.707107  0.791177      1
1 -0.654654 -2.121320 -2.154590      2
2  0.654654  1.414214  1.474667      2
3  1.091089  0.000000  0.157259      2
4 -1.091089  0.000000 -0.109377      1
5 -1.527525 -0.707107 -0.604344      1
6  1.527525  0.000000  0.055111      2
7  0.218218  0.707107  0.390096      0

In [300]:
output2['distance_new1'] = output2[['x1','x2','x3']].sub(np.array(output2.iloc[7:,:3])).pow(2).sum(1).pow(0.5)

In [301]:
output2

x1        x2        x3  class  distance_new1
0 -0.218218  0.707107  0.791177      1       0.592741
1 -0.654654 -2.121320 -2.154590      2       3.903502
2  0.654654  1.414214  1.474667      2       1.366298
3  1.091089  0.000000  0.157259      2       1.147222
4 -1.091089  0.000000 -0.109377      1       1.569637
5 -1.527525 -0.707107 -0.604344      1       2.456935
6  1.527525  0.000000  0.055111      2       1.525287
7  0.218218  0.707107  0.390096      0       0.000000

In [302]:
data3 = [{'x1': 5, 'x2' :0.7, 'x3' :7.200, 'class' :1},{'x1': 4, 'x2' :0.3, 'x3' :3.278, 'class' :2},{'x1': 7, 'x2' :0.8, 'x3' :8.110, 'class' :2}
       ,{'x1': 8, 'x2' :0.6, 'x3' :6.356, 'class' :2},{'x1': 3, 'x2' :0.6, 'x3' :6.001, 'class' :1},{'x1': 2, 'x2' :0.5, 'x3' :5.342, 'class' :1}
       ,{'x1': 9, 'x2' :0.6, 'x3' :6.220, 'class' :2},{'x1': 6, 'x2' :0.7, 'x3' :6.666, 'class' :2},{'x1': 4, 'x2' :0.2, 'x3' :6.320, 'class' :0}]

In [288]:
test3 =pd.DataFrame(data3)

In [289]:
num3 = test3.iloc[:,:-1]

In [290]:
fitted3 = std_scaler.fit(num3)

In [291]:
num3 = std_scaler.transform(num3)

In [292]:
result3 =pd.DataFrame(num3,columns=['x1','x2','x3'])

In [293]:
result3

x1        x2        x3
0 -0.150756  0.788241  0.823049
1 -0.603023 -1.394580 -2.298470
2  0.753778  1.333946  1.547317
3  1.206045  0.242536  0.151309
4 -1.055290  0.242536 -0.131235
5 -1.507557 -0.303170 -0.655733
6  1.658312  0.242536  0.043067
7  0.301511  0.788241  0.398038
8 -0.603023 -1.940285  0.122657

In [303]:
output3 = pd.concat([result3
                     ,test3.iloc[:,-1:]],axis=1)

In [304]:
output3

x1        x2        x3  class
0 -0.150756  0.788241  0.823049      1
1 -0.603023 -1.394580 -2.298470      2
2  0.753778  1.333946  1.547317      2
3  1.206045  0.242536  0.151309      2
4 -1.055290  0.242536 -0.131235      1
5 -1.507557 -0.303170 -0.655733      1
6  1.658312  0.242536  0.043067      2
7  0.301511  0.788241  0.398038      2
8 -0.603023 -1.940285  0.122657      0

In [305]:
output3['distance_new2'] = output3[['x1','x2','x3']].sub(np.array(output3.iloc[8:,:3])).pow(2).sum(1).pow(0.5)

In [306]:
output3

x1        x2        x3  class  distance_new2
0 -0.150756  0.788241  0.823049      1       2.853059
1 -0.603023 -1.394580 -2.298470      2       2.481864
2  0.753778  1.333946  1.547317      2       3.819837
3  1.206045  0.242536  0.151309      2       2.835181
4 -1.055290  0.242536 -0.131235      1       2.243594
5 -1.507557 -0.303170 -0.655733      1       2.025887
6  1.658312  0.242536  0.043067      2       3.143991
7  0.301511  0.788241  0.398038      2       2.887710
8 -0.603023 -1.940285  0.122657      0       0.000000

In [320]:
x1 = np.array([-7,-4,6])

In [332]:
x1_t = np.array([[-7],[-4],[-6]])

In [333]:
x1_t

array([[-7],
       [-4],
       [-6]])

In [336]:
co = np.array([[1,-0.17425,-0.84599],[-0.17425,1,0.144427],[-.084599,0.144427,1]])

In [337]:
co

array([[ 1.      , -0.17425 , -0.84599 ],
       [-0.17425 ,  1.      ,  0.144427],
       [-0.084599,  0.144427,  1.      ]])

In [340]:
answer = np.multiply(x1,co)

In [341]:
answer

array([[-7.      ,  0.697   , -5.07594 ],
       [ 1.21975 , -4.      ,  0.866562],
       [ 0.592193, -0.577708,  6.      ]])

In [342]:
answer = np.multiply(answer,x1_t)

In [343]:
answer

array([[ 49.      ,  -4.879   ,  35.53158 ],
       [ -4.879   ,  16.      ,  -3.466248],
       [ -3.553158,   3.466248, -36.      ]])

In [344]:
np.sqrt(answer)

C:\Users\jaehee\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[7.        ,        nan, 5.96083719],
       [       nan, 4.        ,        nan],
       [       nan, 1.86178624,        nan]])