##### numpy.ndarray로 정의된 데이터를 pandas.dataframe 형태로 전처리하는 예제

In [1]:
# 모듈 불러오기
from sklearn.datasets import load_iris # toy example용 dataset 제공 모듈
import pandas as pd
import numpy as np

In [2]:
# 데이터 불러오기
iris = load_iris()
type(iris) # 딕셔너리 형태로 정의하는 데이터 타입. 자주 활용되는 데이터 타입은 아님 

sklearn.utils.Bunch

In [3]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
print(iris['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
iris['data'][:10] # iris of x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
print('type:', type(iris['data']))
print('shape:', iris['data'].shape)

type: <class 'numpy.ndarray'>
shape: (150, 4)


In [7]:
iris['target'][:10] # iris of y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
print('type:', type(iris['target']))
print('shape:', iris['target'].shape)

type: <class 'numpy.ndarray'>
shape: (150,)


In [9]:
# 데이터 병합
np.concatenate([iris['data'], iris['target']], axis=1) #에러가 발생하는 이유?

ValueError: all the input arrays must have same number of dimensions

In [10]:
# Iris['target']의 크기인 (150, )와 (150,1)은 다름!
# 따라서, iris['target']의 크기를 150x1로 정의 후 다시 데이터 병합을 해야함
merged_iris_array = np.concatenate([iris['data'], iris['target'].reshape(150, 1)], axis=1)
merged_iris_array[:10]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ]])