In [3]:
import numpy as np

##### 배열 속성 확인

In [4]:
x = np.random.randint(10, size = (3,4,5), dtype = 'int8')

In [8]:
print("ndim = ",x.ndim)
print("shape = ",x.shape)
print("size = ",x.size)
print("dtype = ",x.dtype)

ndim =  3
shape =  (3, 4, 5)
size =  60
dtype =  int8


##### 처음부터 배열 만들기

In [9]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.random((3,3))

array([[0.80545067, 0.11744365, 0.24305217],
       [0.33620838, 0.85531042, 0.828166  ],
       [0.20991258, 0.00581128, 0.77677222]])

In [15]:
np.random.normal(0,1,(3,3))

array([[-1.00792256,  0.62338325,  0.24650658],
       [-0.21323859,  0.68710903, -0.09175522],
       [-2.7340952 , -0.1242027 , -0.27126591]])

In [16]:
np.random.randint(0,10,(3,3))

array([[8, 8, 3],
       [2, 6, 3],
       [1, 6, 9]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### 배열 인덱싱

In [19]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [28]:
x1

array([9, 3, 4, 1, 0, 8])

In [26]:
x1[0]

9

In [27]:
x1[-1]

8

In [29]:
x2

array([[8, 0, 3, 9],
       [5, 6, 7, 4],
       [3, 2, 0, 4]])

In [30]:
x2[2,0]

3

In [31]:
x3

array([[[0, 2, 9, 7, 0],
        [4, 8, 8, 6, 3],
        [6, 3, 8, 1, 3],
        [2, 8, 9, 2, 2]],

       [[5, 5, 9, 5, 0],
        [1, 5, 4, 1, 7],
        [9, 1, 3, 0, 7],
        [6, 7, 9, 0, 7]],

       [[9, 0, 7, 1, 2],
        [5, 2, 9, 6, 0],
        [5, 8, 8, 6, 2],
        [3, 5, 5, 0, 1]]])

In [32]:
x3[1,2,3]

0

##### 배열 슬라이싱 - 1차원 하위 배열

In [33]:
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x[:5]

array([0, 1, 2, 3, 4])

In [35]:
x[4:7]

array([4, 5, 6])

In [36]:
x[::2]

array([0, 2, 4, 6, 8])

In [37]:
x[1::2]

array([1, 3, 5, 7, 9])

In [38]:
x[1:8:3]

array([1, 4, 7])

In [39]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

##### 배열 슬라이싱 - 다차원 하위 배열

In [41]:
x = np.random.randint(10, size=(4,5))
x

array([[3, 1, 8, 2, 6],
       [2, 1, 7, 2, 2],
       [9, 9, 8, 0, 8],
       [1, 0, 3, 0, 7]])

In [42]:
x[:2,:3]

array([[3, 1, 8],
       [2, 1, 7]])

In [43]:
x[:,::2]

array([[3, 8, 6],
       [2, 7, 2],
       [9, 8, 8],
       [1, 3, 7]])

In [44]:
x[::-1,::-1]

array([[7, 0, 3, 0, 1],
       [8, 0, 8, 9, 9],
       [2, 2, 7, 1, 2],
       [6, 2, 8, 1, 3]])

##### 같은 차원의 배열 연결

In [47]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[3,2,1],[6,5,4]])

In [48]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
y

array([[3, 2, 1],
       [6, 5, 4]])

In [50]:
np.concatenate([x,y],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4]])

In [51]:
np.concatenate([x,y],axis = 1)

array([[1, 2, 3, 3, 2, 1],
       [4, 5, 6, 6, 5, 4]])

##### 혼합된 차원의 배열 연결

In [55]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[3,2,1],[6,5,4],[3,2,1]])
z = np.array([[7],[10]])

In [53]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
y

array([[3, 2, 1],
       [6, 5, 4],
       [3, 2, 1]])

In [57]:
z

array([[ 7],
       [10]])

In [58]:
np.vstack([x,y])

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4],
       [3, 2, 1]])

In [59]:
np.hstack([x,z])

array([[ 1,  2,  3,  7],
       [ 4,  5,  6, 10]])

##### 배열의 분할

In [60]:
x = np.arange(16).reshape((4,4))

In [61]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
upper, lower = np.vsplit(x,[2])

In [64]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [65]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
left, right = np.hsplit(x,[2])

In [67]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [69]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

##### 비교 연산자 - 기초

In [70]:
x = np.array([1,2,3,4,5])

In [71]:
x<3

array([ True,  True, False, False, False])

In [72]:
x!=3

array([ True,  True, False,  True,  True])

In [73]:
x==3

array([False, False,  True, False, False])

In [75]:
M = np.random.randint(1,10,(3,4))

In [76]:
M < 6

array([[False, False,  True,  True],
       [False, False,  True, False],
       [ True,  True, False,  True]])

##### 부울 배열로 작업하기 - 요소 개수 세기

In [77]:
np.sum(M<6)

6

In [78]:
np.sum(M<6,axis=0)

array([1, 1, 2, 2])

In [79]:
np.sum(M<6,axis=1)

array([2, 1, 3])

In [80]:
np.sum((M>5)&(M<=2))

0

In [81]:
np.sum((M>5)|(M<=2))

7

##### 부울 배열로 작업 하기 - 조건

In [82]:
np.any(M<6)

True

In [83]:
np.all(M<6)

False

##### 마스크로서의 부울 배열

In [84]:
M <5

array([[False, False,  True,  True],
       [False, False,  True, False],
       [ True,  True, False,  True]])

In [85]:
M[M<5]

array([4, 4, 3, 4, 2, 3])

##### 팬시 인덱싱

In [87]:
x = np.random.randint(1,100,size=10)

In [88]:
x

array([70, 55, 43, 64, 17, 15, 58, 55, 59, 20])

In [89]:
ind = [3,7,8]

In [91]:
x[ind]

array([64, 55, 59])

In [92]:
X = np.arange(12).reshape((3,4))

In [93]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
row = np.array([0,1,2])

In [95]:
row

array([0, 1, 2])

In [96]:
col = np.array([2,1,3])

In [97]:
X[row,col]

array([ 2,  5, 11])

##### 팬시 인덱싱으로 값 변경하기

In [99]:
x = np.arange(10)
i = np.array([2,1,8,4])

In [100]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
x[i] = 99

In [102]:
x

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

In [103]:
x[i] -= 10

In [104]:
x

array([ 0, 89, 89,  3, 89,  5,  6,  7, 89,  9])

In [105]:
x = np.zeros(10)

In [106]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
x[[0,1]] = [4,6]

In [108]:
x

array([4., 6., 0., 0., 0., 0., 0., 0., 0., 0.])

In [109]:
x[[0,0]] = [4,6]

In [110]:
x

array([6., 6., 0., 0., 0., 0., 0., 0., 0., 0.])

##### np.sort

In [111]:
x = np.array([2,1,4,3,5])

In [112]:
x

array([2, 1, 4, 3, 5])

In [114]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [121]:
X = np.random.randint(0,10,(4,6))

In [122]:
X

array([[7, 7, 6, 0, 1, 4],
       [6, 7, 5, 4, 8, 7],
       [7, 8, 6, 7, 6, 9],
       [3, 0, 3, 4, 9, 7]])

In [123]:
np.sort(X,axis=0)

array([[3, 0, 3, 0, 1, 4],
       [6, 7, 5, 4, 6, 7],
       [7, 7, 6, 4, 8, 7],
       [7, 8, 6, 7, 9, 9]])

In [124]:
np.sort(X,axis =1)

array([[0, 1, 4, 6, 7, 7],
       [4, 5, 6, 7, 7, 8],
       [6, 6, 7, 7, 8, 9],
       [0, 3, 3, 4, 7, 9]])

In [125]:
-np.sort(-X,axis=0)

array([[7, 8, 6, 7, 9, 9],
       [7, 7, 6, 4, 8, 7],
       [6, 7, 5, 4, 6, 7],
       [3, 0, 3, 0, 1, 4]])